ALTER TABLE game_player_stats ADD COLUMN dunks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game_player_stats ADD COLUMN tips INTEGER NOT NULL DEFAULT 0;

ALTER TABLE game_team_stats ADD COLUMN dunks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game_team_stats ADD COLUMN tips INTEGER NOT NULL DEFAULT 0;

ALTER TABLE season_player_stats ADD COLUMN dunks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE season_player_stats ADD COLUMN tips INTEGER NOT NULL DEFAULT 0;

ALTER TABLE season_team_stats ADD COLUMN dunks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE season_team_stats ADD COLUMN tips INTEGER NOT NULL DEFAULT 0;
